{
 "title": "New dashboard",
 "time": { "from": "2024-03-25T06:15:28.000Z", "to": "2026-03-25T18:15:28.000Z" },
 "panels": [
  {
   "title": "Распределение кол-ва посетителей по дням недели",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "\r\nSELECT\r\nto_char(purchase_date,'Dy') AS weekday,\r\nCOUNT(*) AS tickets\r\nFROM art_galery.tickets\r\nGROUP BY 1\r\nORDER BY tickets DESC;"
    }
   ]
  },
  {
   "title": "Общая выручка музея (руб.)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT SUM(price) as total_revenue\r\nFROM art_galery.tickets;"
    }
   ]
  },
  {
   "title": "Продажи билетов по времени",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\npurchase_date as time,\r\nCOUNT(*) as tickets_sold\r\nFROM art_galery.tickets\r\nGROUP BY purchase_date\r\nORDER BY purchase_date;"
    }
   ]
  },
  {
   "title": "Загрузка филиалов (чел.)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    b.name_branch,\r\n    COUNT(*) AS tickets\r\nFROM art_galery.tickets t\r\nJOIN art_galery.exhibitions e ON t.exhibition_id = e.id\r\nJOIN art_galery.branches b ON e.branch_id = b.id\r\nGROUP BY b.name_branch\r\nORDER BY tickets DESC;"
    }
   ]
  },
  {
   "title": "Выручка по выставкам (руб.)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\ne.name_exhibition,\r\nSUM(t.price) as revenue\r\nFROM art_galery.tickets t\r\nJOIN art_galery.exhibitions e ON t.exhibition_id = e.id\r\nGROUP BY e.name_exhibition\r\nORDER BY revenue DESC;"
    }
   ]
  },
  {
   "title": "Жизненный цикл продаж билетов",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    (t.purchase_date - e.start_date) AS days_before,\r\n    COUNT(*) AS tickets\r\nFROM art_galery.tickets t\r\nJOIN art_galery.exhibitions e\r\nON t.exhibition_id = e.id\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Самые популярные художники по количеству посетителей",
   "type": "barchart",
   "description": "Топ 10",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "\r\nSELECT\r\na.first_name || ' ' || a.last_name as artist,\r\nCOUNT(t.id) as visitors\r\nFROM art_galery.tickets t\r\nJOIN art_galery.exhibitions e ON t.exhibition_id = e.id\r\nJOIN art_galery.exhibit_exhibitions ee ON ee.exhibition_id = e.id\r\nJOIN art_galery.exhibits ex ON ex.id = ee.exhibit_id\r\nJOIN art_galery.artists a ON a.id = ex.artist_id\r\nGROUP BY artist\r\nORDER BY visitors DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Топ 3 посетителей выставок",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 25 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "select\r\n\tv.First_Name,\r\n\tv.Last_Name,\r\n\tcount(t.ID) as Tickets_Count\r\nfrom\r\n\tArt_Galery.Visitors v\r\njoin Art_Galery.Tickets t on\r\n\tv.ID = t.Visitor_ID\r\ngroup by\r\n\tv.ID\r\norder by\r\n\tTickets_Count desc\r\nlimit 3;\r\n\r\n-- находим трех самых активных посетителей"
    }
   ]
  },
  {
   "title": "Распределение цен билетов (руб.)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 31 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "\r\nSELECT price\r\nFROM art_galery.tickets;"
    }
   ]
  },
  {
   "title": "Выручка по выставкам",
   "type": "piechart",
   "description": "Показывает:\nкакой филиал продаёт больше билетов\nдолю каждого филиала",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\nb.name_branch,\r\nCOUNT(t.id) as tickets\r\nFROM art_galery.tickets t\r\nJOIN art_galery.exhibitions e ON t.exhibition_id = e.id\r\nJOIN art_galery.branches b ON e.branch_id = b.id\r\nGROUP BY b.name_branch;"
    }
   ]
  },
  {
   "title": "Загруженность выставок (чел.)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\ne.name_exhibition,\r\nCOUNT(t.id) as visitors\r\nFROM art_galery.tickets t\r\nJOIN art_galery.exhibitions e ON t.exhibition_id = e.id\r\nGROUP BY e.name_exhibition\r\nORDER BY visitors DESC;"
    }
   ]
  }
 ]
}